version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    main: ./cmd/cli
    binary: railpack
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}-v{{ .Version }}-
      {{- if and (eq .Arch "amd64") (eq .Os "darwin") }}x86_64-apple-darwin
      {{- else if and (eq .Arch "arm64") (eq .Os "darwin") }}arm64-apple-darwin
      {{- else if and (eq .Arch "amd64") (eq .Os "linux") }}x86_64-unknown-linux-musl
      {{- else if and (eq .Arch "arm64") (eq .Os "linux") }}arm64-unknown-linux-musl
      {{- else if and (eq .Arch "amd64") (eq .Os "windows") }}x86_64-pc-windows-msvc
      {{- else if and (eq .Arch "arm64") (eq .Os "windows") }}arm64-pc-windows-msvc
      {{- else }}{{ .Arch }}-{{ .Os }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

dockers:
  - image_templates:
      - "{{ .Env.FRONTEND_IMAGE }}:{{ .Tag }}-amd64"
      - "{{ .Env.FRONTEND_IMAGE }}:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    dockerfile: Dockerfiles/frontend.goreleaser.Dockerfile
  - image_templates:
      - "{{ .Env.FRONTEND_IMAGE }}:{{ .Tag }}-arm64"
      - "{{ .Env.FRONTEND_IMAGE }}:latest-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64
    dockerfile: Dockerfiles/frontend.goreleaser.Dockerfile

docker_manifests:
  - name_template: "{{ .Env.FRONTEND_IMAGE }}:{{ .Tag }}"
    image_templates:
      - "{{ .Env.FRONTEND_IMAGE }}:{{ .Tag }}-amd64"
      - "{{ .Env.FRONTEND_IMAGE }}:{{ .Tag }}-arm64"
  - name_template: "{{ .Env.FRONTEND_IMAGE }}:latest"
    image_templates:
      - "{{ .Env.FRONTEND_IMAGE }}:latest-amd64"
      - "{{ .Env.FRONTEND_IMAGE }}:latest-arm64"

changelog:
  use: github-native

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

  name_template: "{{.ProjectName}} v{{.Version}}"

  include_meta: true
